### ISSUE TITLE
libsamplerate-js fix

### ISSUE THREAD

**Issue by aolsenjazz** [juanBerger/postlink-client#1]
Hey juanBerger, just pinging you to say that I've updated libsamplerate-js and you should no longer have to make that manual adaptation in order for it to work. Would love it if you would upgrade to 2.0.3 and verify that this is the case. If not, will again address it.

Thanks!

**Comment by juanBerger** [comment]
@aolsenjazz - This works - many thanks!

**Comment by aolsenjazz** [comment]
Glad to hear it - thanks for checking!
